version: "3.6"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.16.2
    container_name: logstash
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/elastic_to_postgres.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/postgresql-42.7.2.jar:/usr/share/logstash/logstash-core/lib/jars/postgresql-42.7.2.jar
    environment:
      - LS_JAVA_OPTS=-Xmx512m -Xms512m
    ports:
      - "5044:5044"
    command: >
      bash -c "
        logstash-plugin install --no-verify logstash-output-jdbc &&
        logstash -f /usr/share/logstash/pipeline/logstash.conf
      "
